import { L10N, L10NMapper } from ".";

const ENGTexts: L10NMapper = {
  [L10N.HEADER_DEFAULT_01]: "Home",
  [L10N.HEADER_DEFAULT_02]: "My Pill",
  [L10N.HEADER_DEFAULT_03]: "Explore",
  [L10N.HEADER_DEFAULT_04]: "About",

  [L10N.HEADER_CREATE_01]: "Editor",
  [L10N.HEADER_CREATE_02]: "Preview",
  [L10N.HEADER_CREATE_03]: "Save",
  [L10N.HEADER_CREATE_04]: "You must fill all contents to look at the preview.",
  [L10N.HEADER_CREATE_05]: "You must fill all contents to save pill.",
  [L10N.HEADER_CREATE_06]: "Warning",
  [L10N.HEADER_CREATE_07]: "If you leave the create page, everything you've written so far will disappear. Would you like to go on?",
  [L10N.HEADER_CREATE_08]: "Leave",
  [L10N.HEADER_CREATE_09]: "Back to Editor",

  [L10N.PAGE_USER_01]: "What do you want to do now?",
  [L10N.PAGE_USER_02]: "Pill: Latest",
  [L10N.PAGE_USER_03]: "Pill: Most Viewed",
  [L10N.PAGE_USER_04]: "Create New Pill",
  [L10N.PAGE_USER_05]: "'Pill' with your own knowledges and thoughts in your own way!",
  [L10N.PAGE_USER_06]: "Explore Pill",
  [L10N.PAGE_USER_07]: "Are you hungry for knowledge? There is a feast here.",

  [L10N.PAGE_GUEST_01]: "Pill makes it easy to get knowledge. Sign up with just one button and enjoy it!",
  [L10N.PAGE_GUEST_02]: "Sign in with Google",

  [L10N.PAGE_CREATE_01]: "First impression is always important.",
  [L10N.PAGE_CREATE_02]: "Title",
  [L10N.PAGE_CREATE_03]: "Please enter a title.",
  [L10N.PAGE_CREATE_04]: "Category",
  [L10N.PAGE_CREATE_05]: "Add",
  [L10N.PAGE_CREATE_06]: "Enter to Add",
  [L10N.PAGE_CREATE_07]: "Let's fill your Pill.",
  [L10N.PAGE_CREATE_08]: "Add an index",
  [L10N.PAGE_CREATE_09]: "~40 characters",
  [L10N.PAGE_CREATE_10]: "Add a content",
  [L10N.PAGE_CREATE_11]: "Image",
  [L10N.PAGE_CREATE_12]: "Add an image to the end of the index.",
  [L10N.PAGE_CREATE_13]: "Text",
  [L10N.PAGE_CREATE_14]: "Add a text to the end of the index.",
  [L10N.PAGE_CREATE_15]: "Add Image",
  [L10N.PAGE_CREATE_16]: "Enter the image link and press Confirm to check the image in advance.",
  [L10N.PAGE_CREATE_17]: "Image Link",
  [L10N.PAGE_CREATE_18]: "Description",
  [L10N.PAGE_CREATE_19]: "Confirm",
  [L10N.PAGE_CREATE_20]: "Edit",
  [L10N.PAGE_CREATE_21]: "Edit Image",
  [L10N.PAGE_CREATE_22]: "~40 characters",
  [L10N.PAGE_CREATE_23]: "Invalid Image Link.",
  [L10N.PAGE_CREATE_24]: "Done",
  [L10N.PAGE_CREATE_25]: "Image",
  [L10N.PAGE_CREATE_26]: "Text",
  [L10N.PAGE_CREATE_27]: "Up",
  [L10N.PAGE_CREATE_28]: "Down",
  [L10N.PAGE_CREATE_29]: "Edit",
  [L10N.PAGE_CREATE_30]: "Remove",
  [L10N.PAGE_CREATE_31]: "A blank exists.",
  [L10N.PAGE_CREATE_32]: "Great!",

  [L10N.PAGE_EXPLORE_01]: "Look for the Pill you want.",
  [L10N.PAGE_EXPLORE_02]: "If you don't remember the content, try typing the author.",
  [L10N.PAGE_EXPLORE_03]: "All",
  [L10N.PAGE_EXPLORE_04]: "Title",
  [L10N.PAGE_EXPLORE_05]: "Index",
  [L10N.PAGE_EXPLORE_06]: "Content",
  [L10N.PAGE_EXPLORE_07]: "Author",
  [L10N.PAGE_EXPLORE_08]: "{0} Pill(s), {1} Comment(s)",
  [L10N.PAGE_EXPLORE_09]: "{0} elements / page",

  [L10N.PAGE_PREVIEW_01]: "by {0}",
  [L10N.PAGE_PREVIEW_02]: "Indexes",
  [L10N.PAGE_PREVIEW_03]: "Untitled",
  [L10N.PAGE_PREVIEW_04]: "Unknown",

  [L10N.PAGE_NOT_FOUND_01]: "404 - Not Found.",
  [L10N.PAGE_NOT_FOUND_02]: "Back to Home",
  [L10N.PAGE_NOT_FOUND_03]: "Back to Previous Page",

  [L10N.AUTH_01]: "Login",
  [L10N.AUTH_02]: "Logout",

  [L10N.PROFILE_01]: "Guest",

  [L10N.TAB_01]: "Welcome, Guest!",
  [L10N.TAB_02]: "Sign up with just one button without complicated registration process, and enjoy a variety of pills!",
  [L10N.TAB_03]: "Menu",
  [L10N.TAB_04]: "Recent Comments",
  [L10N.TAB_05]: "Recent {0} (+{1})",

  [L10N.TABLET_01]: "Untitled",
  [L10N.TABLET_02]: "Unknown",
} as const;

export default ENGTexts;
